### ISSUE TITLE
Interpolate with IDW radius method

### ISSUE THREAD

**Issue by rtrwalker** [meteoinfo/wContour#1]
I think the following line should be "Interpolate with IDW radius method": 
https://github.com/meteoinfo/wContour/blob/37f75a94aa4cd30788dcf92cbdffd478f9c1edcf/src/wContour/Interpolate.java#L253

**Comment by Yaqiang** [comment]
Yes, you are right. Thanks for figure out it.

**Comment by rtrwalker** [comment]
There is a few others I wasn't sure of.  e.g.   https://github.com/meteoinfo/wContour/blob/37f75a94aa4cd30788dcf92cbdffd478f9c1edcf/src/wContour/Interpolate.java#L330 , should it reads "Interpolation with IDW neighbor method" but the function itself  is "idw_Radius_kdTree".  Maybe just quickly check the first line of all the function descriptions.

**Comment by Yaqiang** [comment]
Thanks for your remind.
