### ISSUE TITLE
Whether the Kriging algorithm is implemented

### ISSUE THREAD

**Issue by kmood** [meteoinfo/wContour#13]
Hello, thank you very much for the open source project, which has brought me a lot of help. I have the following questions: the supported algorithms in the document include Kriging algorithm. There is no implementation of Kriging in the API document.

**Comment by Yaqiang** [comment]
The kriging algorithm is implemented in meteoinfo-math module: https://github.com/meteoinfo/MeteoInfo/blob/master/meteoinfo-math/src/main/java/org/meteoinfo/math/interpolate.

**Comment by kmood** [comment]
OK, thank you
