### ISSUE TITLE
 (系统找不到指定的路径。)

### ISSUE THREAD

**Issue by jovi521** [meteoinfo/wContour#5]
wContour\sample\China.wmp (系统找不到指定的路径。)\
wContour\sample\Prec_2010101420.csv (系统找不到指定的路径。)
当我运行时候会提示路径找不到，是不是少一个sample文件夹？

**Comment by Yaqiang** [comment]
Same with your another issue. So I close this one.

**Comment by jovi521** [comment]
close?......but how can I do?
